### ISSUE TITLE
Stone cairn

### ISSUE THREAD

**Issue by Wivex** [RWA-Team/RimworldAscension#112]
Small decorations, made from stone cobbles. Boosts beauty, as statue or totem, but much easier to build. Require for proper aesthetic look of the colony. Stones should be stuff based. Building is 1x1. 3 variations of textures is preferable.
Don't make them look like "just rock pile" though, or like our "stone cobbles" resource texture:
![stonecobble](https://cloud.githubusercontent.com/assets/13631287/16302425/c2e42d48-3953-11e6-8a11-72d42ef2098f.png)

Examples:
![image](https://cloud.githubusercontent.com/assets/13631287/16301900/c8bab10e-3950-11e6-8ff7-74ec79af88a4.png)
![image](https://cloud.githubusercontent.com/assets/13631287/16301917/dbeb9d4c-3950-11e6-874e-ffc1e587cbfc.png)
![image](https://cloud.githubusercontent.com/assets/13631287/16301969/1dbae0c0-3951-11e6-9123-4dff8ab02874.png)
![image](https://cloud.githubusercontent.com/assets/13631287/16301981/2516972e-3951-11e6-8425-4cde9f151996.png)

**Comment by JackVernian** [comment]
![cairns2](https://cloud.githubusercontent.com/assets/16037085/16310893/9ff647ce-396e-11e6-9fa5-441776acd21a.png)
![cairns](https://cloud.githubusercontent.com/assets/16037085/16309186/2cfe57ee-3968-11e6-9cee-9b29c171d1e0.png)
![cobblearch](https://cloud.githubusercontent.com/assets/16037085/16309188/2f297b02-3968-11e6-863f-2151450b5721.png)
just leaving it here so that it's not lost

**Comment by Wivex** [comment]
![untitled-2 4](https://cloud.githubusercontent.com/assets/13631287/16358542/6c7b7908-3b1e-11e6-9b5b-8273cd8fe1c0.png)
![untitled-2](https://cloud.githubusercontent.com/assets/13631287/16358453/b15de11c-3b1b-11e6-8f08-21c05bfd8da4.png)
![untitled-2 2](https://cloud.githubusercontent.com/assets/13631287/16358454/b15e596c-3b1b-11e6-86cd-49aaf3d99a8a.png)
