### ISSUE TITLE
Suggestions: cooking tools & tree stand

### ISSUE THREAD

**Issue by tommargar** [RWA-Team/RimworldAscension#216]
I suggest adding cooking tools: wooden spoon for cooking and a meat cleaver for butchering.

Also suggesting tree stands https://en.wikipedia.org/wiki/Tree_stand https://upload.wikimedia.org/wikipedia/commons/1/1a/A_rised_hide_closed_quadrat.jpg for hunters. In the German wikipedia version, it says that due to the higher ground, the soil is used to catch the bullets. Might reduce hunting accidents. Might  need a changed animal behaviour, so that the wild life avoids humans in general.

**Comment by Wivex** [comment]
> I suggest adding cooking tools: wooden spoon for cooking and a meat cleaver for butchering.

I'm not intended to add tools for work benches yet.

> Also suggesting tree stands...

Seems like embrasures vs animals. It would make hunting too easy and uninteresting.

**Comment by Tapk0vich** [comment]
Adding tool requirement to too many jobs will clutter gameplay, since pawn can't just carry all instruments he want  in inventory, so pawns will waste a lot of time running for them in case of preparing food. 

As for hunting problems. In long term goals we have work on AI, I think that's when we will solve that problem. As for tree stands, they wont work, cuz animals move, and making player build them all around map is kinda bad solution to problem.
